name: Deploy to OpenShift
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      - name: Deploy application
        run: |
          oc new-app https://github.com/Raju8115/Openshift-project.git
          oc expose svc/openshift-project
