name: Trigger OpenShift Build

on:
  push:
    branches:
      - main

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
  BUILD_NAME: simple-voting-app-git

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}

      - name: Set OpenShift Project
        run: |
          oc project ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Start Build
        run: |
          oc start-build $BUILD_NAME --wait --follow
